# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Author: Robert Zinke
# Copyright (c) 2023, by the California Institute of Technology. ALL RIGHTS
# RESERVED. United States Government Sponsorship acknowledged.
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
import os
import logging
import pickle
import datetime
import shapely
import yaml

import ARIAtools
import ARIAtools.util.log
import ARIAtools.util.shp

LOGGER = logging.getLogger('runlog.py')


class RunLog:
    """
    Track the parameters passed to, or generated by a function or object.
    Parameters relevant to a user for future use will be recorded in a
    human-readable YAML file.
    """
    def __init__(self, workdir, log_level='info'):
        """
        Initialize log directory and files.
        Record basic information such as date and time of run.
        Initialize core parameters.
        """
        # Establish logger
        log_level = {
            'debug': logging.DEBUG, 'info': logging.INFO,
            'warning': logging.WARNING, 'error': logging.ERROR}[log_level]
        logging.basicConfig(level=log_level, format=ARIAtools.util.log.FORMAT)
        LOGGER.info('RunLog')

        # Record parameters
        self.run_time = datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
        self.workdir = os.path.abspath(workdir)

        # Automatically establish log directory and files
        self.log_dir = os.path.join(self.workdir, 'config')
        os.makedirs(self.log_dir, exist_ok=True)

        self.log_name = os.path.join(self.log_dir, 'PICKLE.pkl')
        if not os.path.exists(self.log_name):
            with open(self.log_name, 'wb') as log_file:
                pickle.dump({}, log_file)

        self.config_name = os.path.join(self.log_dir, 'config.yaml')
        if not os.path.exists(self.config_name):
            with open(self.config_name, 'w') as config_file:
                yaml.dump({}, config_file)

        self.file_list_name = os.path.join(self.log_dir, 'files.yaml')
        if not os.path.exists(self.file_list_name):
            with open(self.file_list_name, 'w') as list_file:
                yaml.dump({}, list_file)

        self.extracted_files_name = os.path.join(self.log_dir,
                                                 'extracted_files.yaml')
        if not os.path.exists(self.extracted_files_name):
            with open(self.extracted_files_name, 'w') as extr_file:
                yaml.dump({}, extr_file)

        # Automatically update core parameters
        self.__update_runtimes__()
        self.update('workdir', self.workdir)
        self.update('update_mode', 'full_extract')

    def load(self):
        """ Load all data from PICKLE file. """
        with open(self.log_name, 'rb') as log_file:
            log_data = pickle.load(log_file)

        return log_data

    def update(self, attr_name, attr_value):
        """
        Write (serialize) the specified parameter to PICKLE file.
        attr_name is the name of the attribute to be recorded (string)
        attr_value is the attibute to be written (can be any type for PICKLE)
        """
        # Recall existing log data
        log_data = self.load()

        LOGGER.debug('Writing %s to log file', attr_name)

        # Check if previous version of attribute should be saved
        if attr_name in ['total_bbox', 'total_bbox_metadatalyr']:
            if attr_name in log_data.keys():
                log_data[f'prev_{attr_name}'] = log_data[attr_name]

        # Check if attributes should be written to YAML file
        if attr_name == 'run_times':
            self.__update_configs__('run_times', attr_value)

        elif attr_name in ['aria_version', 'aria_routine']:
            self.__update_configs__(attr_name, attr_value)

        elif attr_name == 'args':
            attrs = attr_value.__dict__
            config_params = ['input_params', 'workdir', 'bbox', 'croptounion',
                             'multilooking', 'minimumOveralp', 'nc_version',
                             'projection']
            for param in config_params:
                if param in attrs.keys():
                    self.__update_configs__(param, attrs[param])

        if attr_name == 'files':
            self.__write_file_list__(attr_value)

        if attr_name == 'extracted_files':
            self.__write_extracted_files__(attr_value)

        # Write new log data
        log_data[attr_name] = attr_value
        with open(self.log_name, 'wb') as log_file:
            pickle.dump(log_data, log_file)

    def __update_runtimes__(self):
        """
        Append a new run date and time list of previous runtimes, for both
        the PICKLE file and the user-readable YAML file.
        In most cases, this function will only be called once at the time
        of object instantiation.
        """
        # Retrieve existing data
        log_data = self.load()

        if 'run_times' in log_data.keys():
            log_data['run_times'].append(self.run_time)
        else:
            log_data['run_times'] = [self.run_time]

        self.update('run_times', log_data['run_times'])

    def __update_configs__(self, attr_name, attr_value):
        """
        Update the YAML configuration file with the specified attribute and
        value.
        """
        # Convert shapely polygon to WKT
        if type(attr_value) == shapely.Polygon:
            attr_value = attr_value.wkt

        # Recall existing config data
        with open(self.config_name, 'r') as config_file:
            config_data = yaml.safe_load(config_file)

        # Write new data
        config_data[attr_name] = attr_value
        with open(self.config_name, 'w') as config_file:
            yaml.dump(config_data, config_file)

    def __write_file_list__(self, files):
        """ Write list of files read in to YAML. """
        # Write new data
        with open(self.file_list_name, 'w') as list_file:
            yaml.dump({'files': files}, list_file)

    def __write_extracted_files__(self, extracted_files):
        """ Write list of extracted files to YAML. """
        extr_dict = {'extracted_files': extracted_files,
                     'nb_extracted': len(extracted_files)}
        with open(self.extracted_files_name, 'w') as extr_file:
            yaml.dump(extr_dict, extr_file)
